functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
 - При выборе языка, (Русский, English) сайт должен полностью изменить язык, на выбранный (Категории, Производитель, Описание товара)
 - При выборе языка  English должен быть изображен Британский флажок
 - Пользователь должен иметь возможность зарегистрироваться 
 - Пользователь должен иметь возможность авторизоваться
 - Пользователь должен иметь возможность фильтровать товары по цене, рейтингу
 - При выборе чекбокса "В наличии" должны отображаться товары
 - При добавлении товаров в корзину, пользователь должен иметь возможность выбрать количество товаров
 - При оформлении заказа, должна быть возможность выбрать необходимые товары для заказа из корзины
 - При оформлении заказа, должна быть возможность оставить контактные данные для связи
 - При оформлении заказа, должна быть возможность выбрать доставку
 - После оформления заказа корзина должна очищаться
 - После оформления заказа, должны быть вкладка "Заказы" где пользователь может ознакомитсья с заказами

